### ISSUE TITLE
Exception 'Exists' object has no attribute 'rhs'

### ISSUE THREAD

**Issue by shield007** [noripyt/django-cachalot#156]
## What happened?

We are running django-cachalot in production and keep getting exceptions "'Exists' object has no attribute 'rhs'". This is captured in sentry, so we can see some of the details.

It's comming from the following line in cachalot/utils.py:
```rhs = child.rhs```

Here are some of the details set at this point:

* child - django.db.models.expressions.Exists object
* child_class - django.db.models.expressions.Exists
* children - [django.db.models.lookups.Exact,django.db.models.expressions.Exists]
* rhs -  uuid.UUID
* rhs_class - uuid.UUID

## What should've happened instead?

No exception

## Steps to reproduce

Seems to happen on DB quieries that make use of django.db.models.expressions.Exists.

Django==3.0.6
Postgres DB (12.x)

**Comment by Andrew-Chen-Wang** [comment]
Interesting. Are you on Cachalot 2.2.0, the latest? It seemed like a
problem post Django 2.2 and it should’ve been fixed... Will look into it if
it’s not the version issue.

**Comment by shield007** [comment]
Yes, we should be on the latest. I have the django-cachalot==2.2.0 in the requirements file.

**Comment by Andrew-Chen-Wang** [comment]
@shield007 Hm. #132 (that was merged in a different commit) was supposed to fix Django's extensions. I'll look into it. Do you mind posting traceback? It's fine if you don't; you may not need to.

**Comment by shield007** [comment]
@Andrew-Chen-Wang  Sure, here is the traceback we got, I've striped out the lins from our code base. But if thats a problem let me know. It's probally fine to include them. Just taking them out while they are not needed:

AttributeError: 'Exists' object has no attribute 'rhs'
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "newrelic/hooks/framework_django.py", line 540, in wrapper
    return wrapped(*args, **kwargs)
<removed application code>
  File "django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
<removed application code>
  File "newrelic/hooks/framework_django.py", line 931, in wrapper
    return wrapped(*args, **kwargs)
  File "django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
<removed application code>
  File "django/db/models/query.py", line 276, in __iter__
    self._fetch_all()
  File "django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "cachalot/monkey_patch.py", line 36, in inner
    return original(compiler, *args, **kwargs)
  File "cachalot/monkey_patch.py", line 83, in inner
    table_cache_keys = _get_table_cache_keys(compiler)
  File "cachalot/utils.py", line 196, in _get_table_cache_keys
    for t in _get_tables(db_alias, compiler.query)]
  File "cachalot/utils.py", line 172, in _get_tables
    for subquery in _find_subqueries_in_where(query.where.children):
  File "cachalot/utils.py", line 117, in _find_subqueries_in_where
    rhs = child.rhs

**Comment by shield007** [comment]
Also dobule checked the running version and it is indeed 2.2.0.

```/app # pip freeze | grep cachalot
django-cachalot==2.2.0```

**Comment by Andrew-Chen-Wang** [comment]
@shield007 Thanks for adding your traceback. I understand the problem. Please look out for cachalot 2.2.2. The problem WAS fixed, but I apparently didn't put it in cachalot 2.2.0. It's actually fixed in master branch. Sorry for the inconvenience. That patch for 2.2.2 should come out today.

**Comment by Andrew-Chen-Wang** [comment]
@shield007 I'm going to close this issue now since I just published version 2.2.2 which should come with the fix. Sorry for the inconvenience! Please reopen this if the issue persists.

**Comment by shield007** [comment]
Thanks for looking into it. Will test 2.2.2 today.

**Comment by shield007** [comment]
We still see problems with the 2.2.2 relase. Here is a stack we are getting:

**Comment by shield007** [comment]
Can this issue be reopened ?

**Comment by Andrew-Chen-Wang** [comment]
I see. Same problem. Perhaps, if we moved the subquery into the try block?

**Comment by shield007** [comment]
I've looked into this a bit, I know have some code to reproduce the problem from the django shell. From what I can see the main issue is that on line 117, `rhs = child.rhs`. The problem is that the child does not have a property rhs because child.__class__ is actually django.db.models.expressions.Exists.

**Comment by shield007** [comment]
I've now created a pull request, https://github.com/noripyt/django-cachalot/pull/157. This fixes it for me. Hopefully this helps with the issue.

**Comment by Andrew-Chen-Wang** [comment]
@shield007 Yes, but I didn't want #157 to invalidate Exists subqueries from working with cachalot. The deleted lines in your PR was there so that your subquery could work with cachalot in Django 2.2. I'd much rather find a solution to getting it to work than for it to not work. You can use #155 whenever someone gets around to working on disabling cachalot temporarily via a context manager. Hopefully soon from my end.

**Comment by Andrew-Chen-Wang** [comment]
@shield007 I've merged your PR for version 2.3.0. If it's still not working, you can use the new context manager to disable cachalot. Please let me know if there are any problems.

**Comment by Andrew-Chen-Wang** [comment]
ping
