### ISSUE TITLE
Django 3.2 is not compatible with this version of django-cachalot

### ISSUE THREAD

**Issue by zelnkup** [noripyt/django-cachalot#175]
## Description

[//]: # (What are you proposing and how would we implement it?)

## Rationale

[//]: # (Why should this be implemented?)

**Comment by Andrew-Chen-Wang** [comment]
Thank you for the heads up. I will be AWOL this week with school work, but I should be gtg next week to update the package with support for 3.2.

**Comment by Natureshadow** [comment]
I do not see why there should be any issues with Django 3.2.

I propose to jsut drop the system check and instead fix the dependency (after all, the dependency defined in your `setup.py` does not limit the Django version).

I will make a pull request fixing this up, and I propose moving django-cachalot to the jazzband team for team maintenance. if you do not want to do that, I offer co-maintenance. outside the jazzband team.

**Comment by Natureshadow** [comment]
I removed the system check altogether, reationale in #177.

The worst thing here is that the dependency in `requirements.txt` is out of sync with the system check, meaning that `pip` will auto-upgrade to a Django version the system check will not accept, breaking existing systems!

So if my PR is not accepted, please ensure that the dependency is in sync with the check.

**Comment by Andrew-Chen-Wang** [comment]
If the version check annoys your team, visit the Django docs to mute the warning. Otherwise:

> I do not see why there should be any issues with Django 3.2.

"Should," yet last time when I added support for Django 3.1, sure nothing broke, but lots of things changed. That meant people's CIs were going bonkers with deprecation warnings and no one really likes muting their DjangoDeprecationWarnings in their pytests. Here's the specific commit where lots of things changed: https://github.com/noripyt/django-cachalot/commit/d699c5b8c3394e2d2ca35cb4f800deff56a0079c

And that is why we have a system check. Because we monkey patch the sh*t out of Django, the most crucial part, the ORM, so we're really trying not to mess anything up. That's the reason we have Tox tests for multiple Django versions (really regardless of the package) and that's why in Django package READMEs we write which versions of Django we support.

I would definitely welcome a PR though! Any help is greatly appreciated for a broke college student!

> I propose moving django-cachalot to the jazzband team for team maintenance

I want to see what happens first with another package that was recently migrated to Jazzband. If anything, I'm getting busier, so I'll definitely consider your latter offer, but for now, please be patient. Thanks.

**Comment by Natureshadow** [comment]
>And that is why we have a system check. Because we monkey patch the sh*t out of Django, the most crucial part, the ORM, so we're really trying not to mess anything up. That's the reason we have Tox tests for multiple Django versions (really regardless of the package) and that's why in Django package READMEs we write which versions of Django we support.

Ok, I understand why you want to limit the Django version more strictly than usual.

But I still think doing so using the dependency system is enough, and that at the very least the dependency should match the check, in order to prevent environment from breaking during a regular update even without overriding dependencies.

I will update my PR accordingly.

Another middle way could be to make the check a warning.

**Comment by Andrew-Chen-Wang** [comment]
Disabling this check can be done with `SILENCED_SYSTEM_CHECKS = ["cachalot.E003"]`

The Django 3.2 warning should not generate any CI or `runserver` failure, so I'm not sure what you mean by " in order to prevent environment from breaking during a regular update even without overriding dependencies." Mind elaborating?

**Comment by hansegucker** [comment]
> The Django 3.2 warning should not generate any CI or runserver failure, so I'm not sure what you mean by " in order to prevent environment from breaking during a regular update even without overriding dependencies." Mind elaborating?

If you don't silence the system check, it definitely will cause a failure on starting the (dev) server because the system check currently doesn't return a warning, but an error. 

See also https://docs.djangoproject.com/en/3.2/ref/checks/#django.core.checks.CheckMessage

**Comment by Natureshadow** [comment]
> Disabling this check can be done with `SILENCED_SYSTEM_CHECKS = ["cachalot.E003"]`

Yes, this will work, but I don't think it is very clean, and it contradicts quite a few theses from the Zen of Python ;).

Again, putting constraints on dependencies is what dependency constraints are for. That's the one obvious way to do it.

> The Django 3.2 warning should not generate any CI or `runserver` failure, so I'm not sure what you mean by " in order to prevent environment from breaking during a regular update even without overriding dependencies." Mind elaborating?

A **warning** should not do that, right, but as @hansegucker said, it is an **error**, and system check errors are designed to abort Django startup, and it does just that, as expected.

**Comment by Natureshadow** [comment]
I updated my PR to further limit the dependency, and adding a note to README explaining the compatibility situation and why simply adherin to semver is not enough.

**Comment by pulse-mind** [comment]
Hello,

I tried to use your branch @Natureshadow on my application so then the application started but then I've got some errors during execution. Some parts of the applications are working fine but some not. It was working fine on Django 3.1, this is an example : 
```
...
  File "D:\Perso\Projects\xxxxx\xxx\items\admin.py", line 994, in change_view
    purchaseorder_totals = purchaseorder_lines.aggregate(
  File "D:\Perso\VirtualEnv\xxxxx\lib\site-packages\django\db\models\query.py", line 399, in aggregate
    return query.get_aggregation(self.db, kwargs)
  File "D:\Perso\VirtualEnv\xxxxx\lib\site-packages\django\db\models\sql\query.py", line 511, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "d:\perso\virtualenv\xxxxx\src\django-cachalot\cachalot\monkey_patch.py", line 29, in inner
    return original(compiler, *args, **kwargs)
  File "d:\perso\virtualenv\xxxxx\src\django-cachalot\cachalot\monkey_patch.py", line 84, in inner
    table_cache_keys = _get_table_cache_keys(compiler)
  File "d:\perso\virtualenv\xxxxx\src\django-cachalot\cachalot\utils.py", line 191, in _get_table_cache_keys
    for t in _get_tables(db_alias, compiler.query)]
  File "d:\perso\virtualenv\xxxxx\src\django-cachalot\cachalot\utils.py", line 172, in _get_tables
    _get_tables_from_sql(connections[db_alias], query.subquery))
  File "d:\perso\virtualenv\xxxxx\src\django-cachalot\cachalot\utils.py", line 99, in _get_tables_from_sql
    return {t for t in connection.introspection.django_table_names()
  File "d:\perso\virtualenv\xxxxx\src\django-cachalot\cachalot\utils.py", line 100, in <setcomp>
    if t in lowercased_sql}
TypeError: argument of type 'bool' is not iterable```

**Comment by Natureshadow** [comment]
In that case, we should at "test suite is incomplete" to the list of issues ;).

The scope of my PR is to remove the unnecessary system check and fix the dependency to select the supported Django versions; I added 3.2 to the supported versions because the test suite succeeds with 3.2.

**Comment by pulse-mind** [comment]
I added a new issue about the test suite : https://github.com/noripyt/django-cachalot/issues/180
Anyway the PR does not resolve this current issue about django 3.2, it is still incompatible with the PR.

**Comment by Andrew-Chen-Wang** [comment]
v2.4.0 is now out. Thanks for all your patience everyone!
